@host = localhost:8080
@ownerId = 8688e068-0ef7-4a6d-b049-85acb31f1b70
@petId = 24a36a98-b75d-465d-a68d-e3b0bbcdbff6

####################################################################################
###################### GET ALL OWNERS (WORKS?) #####################################
####################################################################################
# @name getAllOwners
GET http://{{host}}/api/owners
Content-Type: application/json

####################################################################################
###################### GET OWNER BY ID (WORKS?) ####################################
####################################################################################
# @name getSingleOwner
GET http://{{host}}/api/owners/{{ownerId}}
Content-Type: application/json

####################################################################################
###################### CREATE OWNER ############################################
####################################################################################
# @name createOwner
POST http://{{host}}/api/owners
Content-Type: application/json

{
  "name": "Tamara",
  "surname": "Mruk",
  "phoneNumber": 123456789,
  "dateOfBirth": "2004-12-29",
  "address": "123 Maple St, Anytown"
}

####################################################################################
###################### UPDATE OWNER ############################################
####################################################################################
# @name updateOwner
PUT http://{{host}}/api/owners/{{ownerId}}
Content-Type: application/json

{
  "name": "Ciamara",
  "surname": "Mruk",
  "phoneNumber": 123456789,
  "dateOfBirth": "2004-12-29",
  "address": "123 Maple St, Anytown"
}

####################################################################################
###################### DELETE OWNER ############################################
####################################################################################
# @name deleteOwner
DELETE http://{{host}}/api/owners/{{ownerId}}
Content-Type: application/json

####################################################################################
###################### GET ALL PETS ################################################
####################################################################################
# @name getAllPets
GET http://{{host}}/api/pets
Content-Type: application/json

####################################################################################
###################### GET ALL PETS OF OWNER #######################################
####################################################################################
# @name getAllOwnerPets
GET http://{{host}}/api/owners/{{ownerId}}/pets
Content-Type: application/json

####################################################################################
###################### GET PET BY ID ###############################################
####################################################################################
# @name getSinglePet
GET http://{{host}}/api/pets/{{petId}}
Content-Type: application/json

####################################################################################
###################### CREATE PET ##################################################
####################################################################################
# @name createPet
POST http://{{host}}/api/pets
Content-Type: application/json

{
    "name": "Pandora",
    "animal": "CAT",
    "dateOfBirth": "2016-04-18T00:00:00.000+00:00",
    "weight": 2.2,
    "breed": "Siamese",
    "color": "Creme/Brown",
    "gender": "FEMALE",
    "ownerId": "{{ownerId}}"
}

####################################################################################
###################### UPDATE PET ##################################################
####################################################################################
# @name updatePet
PUT http://{{host}}/api/pets/{{petId}}
Content-Type: application/json

{
    "name": "Mimi",
    "animal": "CAT",
    "dateOfBirth": "2016-04-18T00:00:00.000+00:00",
    "weight": 2.2,
    "breed": "Siamese",
    "color": "Creme/Brown",
    "gender": "FEMALE",
    "ownerId": "{{ownerId}}"
}

####################################################################################
###################### DELETE PET ##################################################
####################################################################################
# @name deletePet
DELETE http://{{host}}/api/pets/{{petId}}
Content-Type: application/json
