### Global Variables
@host = localhost:8080
@ownerId = dcc6ec36-cc82-437b-a805-ab9f723fe31d
@petId = 88cc1e07-7922-41a0-9353-75f8efbb4be4

####################################################################################
###################### CREATE PET OWNER ##########################################
####################################################################################
# @name createOwner
POST http://{{host}}/api/owners
Content-Type: application/json

{
  "name": "Bruh",
  "surname": "Bruh",
  "phoneNumber": 123456789,
  "dateOfBirth": "1990-12-12",
  "address": "123 Maple St, Anytown"
}

####################################################################################
###################### GET ALL PET OWNERS ##########################################
####################################################################################
# @name getAllOwners
GET http://{{host}}/api/owners

####################################################################################
###################### GET PET OWNER BY ID #########################################
####################################################################################
# @name getSingleOwner
GET http://{{host}}/api/owners/{{ownerId}}

#################################################################################
###################### UPDATE PET OWNER #########################################
#################################################################################
# @name updateOwner
PUT http://{{host}}/api/owners/{{ownerId}}
Content-Type: application/json

{
  "name": "Bruhh",
  "surname": "Bruhh",
  "phoneNumber": 987654321,
  "dateOfBirth": "1990-05-15T00:00:00.000+00:00",
  "address": "456 Oak St, New City"
}

#################################################################################
###################### GET PETS OF OWNER BY ID ##################################
#################################################################################
# @name getPetsOfOwner
GET http://{{host}}/api/owners/{{ownerId}}/pets

####################################################################################
###################### CREATE PET ##################################################
####################################################################################
# @name createPet
POST http://{{host}}/api/pets
Content-Type: application/json

{
    "name": "Sparky",
    "animal": "DOG",
    "dateOfBirth": "2022-10-20T00:00:00.000+00:00",
    "weight": 5.5,
    "breed": "Beagle",
    "color": "Brown/White",
    "gender": "FEMALE",
    "ownerId": "{{ownerId}}"
}

####################################################################################
###################### CREATE PET WITH WRONG OWNER ID ##############################
####################################################################################
# @name createPetWrongOwnerId
POST http://{{host}}/api/pets
Content-Type: application/json

{
  "name": "Ghost",
  "animal": "CAT",
  "ownerId": "00000000-0000-0000-0000-000000000000"
}

####################################################################################
###################### GET ALL PETS ################################################
####################################################################################
# @name getAllPets
GET http://{{host}}/api/pets

####################################################################################
###################### GET SINGLE PET BY ID ########################################
####################################################################################
# @name getSinglePet
GET http://{{host}}/api/pets/{{petId}}

####################################################################################
###################### UPDATE PET ##################################################
####################################################################################
# @name updatePet
PUT http://{{host}}/api/pets/{{petId}}
Content-Type: application/json

{
    "name": "Sparky V2",
    "animal": "DOG",
    "dateOfBirth": "2022-10-20T00:00:00.000+00:00",
    "weight": 6.1,
    "breed": "Beagle Mix",
    "color": "Tricolor",
    "gender": "FEMALE",
    "ownerId": "{{ownerId}}"
}

####################################################################################
###################### DELETE PET ##################################################
####################################################################################
# @name deletePet
DELETE http://{{host}}/api/pets/{{petId}}

####################################################################################
###################### DELETE OWNER ################################################
####################################################################################
# @name deleteOwner
DELETE http://{{host}}/api/owners/{{ownerId}}
